### ISSUE TITLE
nighty build 165-69813a5 to 3.16.2.0RC1 upgrade FAIL!

### ISSUE THREAD

**Issue by mathisono** [aredn/aredn_ar71xx#148]
I pushed the nighty build 165-69813a5 2 weeks ago too 2 regularly supported devices , as of tonight the upload button stays grayed out after i select the .bin 
Idea???

**Comment by dman776** [comment]
Check the help file and disable all tunnel connections

**Comment by mathisono** [comment]
http://downloads.arednmesh.org/releases/3/16/3.16.2.0RC1/ar71xx/ 

Its nice to see a readme in the download link !!!

I will try disabling the Tunnel'in, and give it a try...

**Comment by mathisono** [comment]
Ok that did the trick
