### ISSUE TITLE
PBEM5-300 Name Doesn't Display on MESH Neighbor List (only I.P. addy displays)

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn_ar71xx#153]
Name doesn't display on neighbor list- only I.P. addy AREDN 186 and previous nightly builds.
Screen shot:
![image](https://user-images.githubusercontent.com/42675931/44589209-8d68b400-a77d-11e8-8516-f225d35f1d84.png)
Support data available but won't upload as unsupported file type?
File provided to K5DLQ 8/24/18

**Comment by k1ky** [comment]
Looks like it may be "fixed" with Nightly 192!
![image](https://user-images.githubusercontent.com/42675931/44593729-d6bf0080-a789-11e8-9559-70c74391ef19.png)

**Comment by k1ky** [comment]
It's back to IP addy display again with AREDN-200 on both ends.
![image](https://user-images.githubusercontent.com/42675931/44664207-2f83d880-a9d8-11e8-9501-5366533168e1.png)

**Comment by k1ky** [comment]
I'll try 206 and report back.

**Comment by k1ky** [comment]
Back to working properly with 206 installed on the Powerbeam: 
![image](https://user-images.githubusercontent.com/42675931/44667265-f18ab280-a9df-11e8-8dd7-ef034050c598.png)

**Comment by k1ky** [comment]
After 206 the node name reverted back to being reported as IP addy only on all subsequent Nightly releases. Installed 247 today and the node name displays correctly again.

**Comment by ae6xe** [comment]
I have observed this symptom infrequently come and go with the same build number.   On one occasion I inspected the OLSR packets and settings for OLSR.    Correct settings, but OLSR did not communicate (name services plugin) its own hostname to neighbors.     I did a "/etc/init.d/olsrd restart" and found the symptom went away.    Try this the next to you see a symptom to confirm an olsr restart resolves the issue.    I suspect this is an OLSR bug.

**Comment by ae6xe** [comment]
This is likely https://github.com/aredn/aredn_ar71xx/issues/206.   Will close this as duplicate.

**Comment by k1ky** [comment]
I think you mean to refer to #204 as duplicate?  not sure what this would have to do with #206?

**Comment by ae6xe** [comment]
Yes, corrected.
