### ISSUE TITLE
Feature Request - Disable RF deck option in user interface

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn_ar71xx#155]
When operating in congested areas with multiple nodes connected via DTD in a close environment, it is desirable to disable the RF deck in order to reduce congestion on the network.  Leaving the "option" to re-enable RF when needed.  Alternative would be to set a different SSID and reduce power,  but would rather get rid of the extra RF when not needed and have the node available for service.  This can be handy when extra nodes are serving as Tunnel Clients and Servers to further reduce the workload.

**Comment by dman776** [comment]
Fixed in PR#307
