### ISSUE TITLE
Please add "Just flashed" reset from software

### ISSUE THREAD

**Issue by KC6RKG** [aredn/aredn_ar71xx#162]
Can we have a "just flashed" reset option through the AREDN software for those resets that need to take place when nodes are hard to reach... like on a roof or a tower and you can't easily push the reset button for 15 seconds?

**Comment by dman776** [comment]
two options:
1) use the reset button on the bottom of most UBNT PoE adapters
2) ssh into the node and issue these commands:    firstboot -y && reboot

**Comment by ae6xe** [comment]
Is  the #2 option sufficient, or is this a request to hook this into a UI option?
