### ISSUE TITLE
Add Refresh Feature to AREDN Online Map

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn_ar71xx#198]
Requesting a "Refresh" feature on the ONLINE AREDN Map which will retain the position, zoom level, etc. when viewing nodes.  This would be desirable when working with node updates to verify correct positioning and publication of node locations.  The current method of "reloading" a page requires the user to re-position and zoom in on the area of interest.

**Comment by dman776** [comment]
Google Earth does this (and more) if you link the KML files

Thanks,
Darryl

**Comment by k1ky** [comment]
Thanks for the tip Darryl, I do this with APRS.fi, didn't think about trying this with the AREDN map files. I'll give it a try.  I still believe my suggestion above would be a good enhancement.

**Comment by k1ky** [comment]
The KG6WXC MeshMap product has the ability to fix coordinates and zoom level to the web address.  Would that be a viable solution/option?

**Comment by dman776** [comment]
Also if I recall correctly you can include.  &lat=xxxx?lon=yyyy?z=n. On the url

For lat, lon, and zoom level

Thanks,
Darryl

**Comment by k1ky** [comment]
What "format" are the coordinates? Zoom level parameters?  Can you provide a working example?

**Comment by dman776** [comment]
https://www.arednmesh.org/content/31610-map-file-access

**Comment by k1ky** [comment]
So as an Example for Nashville:
http://usercontent.arednmesh.org/K/5/K5DLQ/livemap2.html?zoom=3&lat=36.14&lon=-86.8&z=11
I can do a web browser reload and the map refreshes based on the provided coordinates and zoom level chosen.  That gets pretty close to what I was looking for.  If only the map would populate the browser addy with this information based on the current viewing position etc,. that would be perfect.

**Comment by dman776** [comment]
@r1de fixed it!
