### ISSUE TITLE
Feature Request - Verify Node Board id before upgrading Firmware - match Firmware to appropriate Model for compatibility

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn_ar71xx#206]
Request that firmware compatibility to node make/model/board id type be checked before upgrading. If nothing more than a "warning" of possible incompatibility such as installing XM firmware on an XW device, mismatched Model i.e. installing Rocket Firmware on a Nanostation for example.

On several occasions even the most experienced user can accidentally install upgrade firmware on remote nodes, rendering them as "bricks", sometimes requiring a trip up a tower or a long trip to a remote site.

I can see situations where a total "lockout" for upgrading would not be preferable, but at least some sort of compatibility detection with a warning could avert imminent upgrade disaster.

**Comment by ae6xe** [comment]
Been there, done that.

**Comment by k1ky** [comment]
This could be accomplished by comparing for some sort of type match against the already installed firmware.  If different - provide a warning and confirmation to proceed.

**Comment by dman776** [comment]
For a simple check, we could just verify the filename that the user is attempting to load.   ie:

<script>
	function validate(elem){
    var alphaExp = /.*-rocket-m-xw-sysupgrade.bin$/;
    if(elem.value.match(alphaExp)){
        return true;
    }else{
    	if (confirm('This filename is NOT appropriate for this device!  Are you sure you want to continue?')) {
 			return true;
		} else {
			elem.value="";
	        return false;
		}
    }
}
</script>
<input type="file" title="My File" name="myfile" accept=".bin" onchange="validate(this)" />

--------
This would mean that users would be warned if they renamed the files to something that would not comply with this check, but, they would still have the opportunity to override it by clicking CONTINUE.
