### ISSUE TITLE
Excessive Load on node

### ISSUE THREAD

**Issue by Orv** [aredn/aredn_ar71xx#209]
Vanilla NSM5 running 3.18.9.0 - DtD connected to many nodes.  Only 4 RF connections.   UI was unresponsive (although it was passing traffic to remote nodes).
Found load of 6 on CPU.   Rebooting resolved issue.
How to troubleshoot in future if it reoccurs?

**Comment by ae6xe** [comment]
Orv, let's consolidate this to https://github.com/aredn/aredn_ar71xx/issues/207 .
