### ISSUE TITLE
Avoid duplicate hostnames when reserving IP addresses

### ISSUE THREAD

**Issue by ae6xe** [aredn/aredn_ar71xx#216]
Generic hostnames can be created across the mesh network, e.g. "RPi", "RasPBX", "ipCam", etc.,   If duplicate, one device may not be reachable.    Check if an existing hostname already exists for reserving an IP address.

**Comment by r1de** [comment]
What about just a note, some text: "You are encouraged to prefix your hostnames with a callsign, be it a club or individual, this will ensure all hostnames are unique"

**Comment by AlyBadawy** [comment]
Thanks for this, and I see this was already patched. For the scenario above, but what about if the two nodes with such services are not linked until after the services names have already been setup?

**Comment by ae6xe** [comment]
There's only an opportunity to test for duplicate hostnames after the fact when both nodes become live at the same time on a common mesh network.  We should be able to find the condition and report in mesh status to bring about awareness,
