### ISSUE TITLE
Turn power on/off on USB port if available on a device

### ISSUE THREAD

**Issue by ae6xe** [aredn/aredn_ar71xx#241]
Devices with USB ports might be used to power a local RasPi or other devices.   Enable an advanced setting to turn USB power on/off.  

to manually do this on the hAP AC lite device:
echo 45 > /sys/class/gpio/export           # if /sys/class/gpio//gpio45 does not exist
echo 1 > /sys/class/gpio/gpio45/value  # to turn on
echo 0 > /sys/class/gpio/gpio45/value  # to turn off
Be sure to stay within the hAP AC lite specs of 1A on the USB port.

**Comment by Orv** [comment]
Is this persistent, Joe?

**Comment by ae6xe** [comment]
No, not persistent.

**Comment by dman776** [comment]
Once this feature is implemented it will be persistent 

Thanks,
Darryl

**Comment by AC0WN** [comment]
Tested and works great.  Looking forward to the implementation.  :)

Thanks,
julie
