### ISSUE TITLE
Disable check for tunnels before allowing firmware uploads on 64MB devices

### ISSUE THREAD

**Issue by r1de** [aredn/aredn_ar71xx#254]
Since we're dealing a lot more with 64MB devices the check for tunnels, which disables the firmware upload button on the admin page, should be for 32MB devices only.
There should (I'd think), almost always be enough space on a 64MB device, so why check?

I'm sure there are several ways this could be done.

(just getting it here since I just thought of it)

**Comment by dman776** [comment]
This is denial of service threat mitigation.  Not a low memory issue

Thanks,
Darryl

**Comment by r1de** [comment]
I understood it completely wrong then... nevermind. :)
