### ISSUE TITLE
Auto wifi scan using javascript

### ISSUE THREAD

**Issue by raysuelzer** [aredn/aredn_ar71xx#264]
Hey, 

I'm a front end web developer.  How would you feel about me taking a stab at implementing a javascript based autoscan feature that would update the page via ajax instead of meta-refreshes?  It would probably run faster and require less data over the air.

KM6WUH (soon to be KK6RAY)
Ray

**Comment by ae6xe** [comment]
Ray,  YES.   please contact separately  ae6xe at arrl dot net.   We would love to rebuild a lot of the UI as the current perl generated pages are not very efficient, a memory hog, and don't get us started...  :) .  Let's further discuss.

**Comment by dman776** [comment]
Reviewing this for a new UI approach with Ray.

**Comment by dman776** [comment]
closing.   addressed with #379 and in aredn_ui PR#12
