### ISSUE TITLE
Unresponsive UI with recent nightly build

### ISSUE THREAD

**Issue by Orv** [aredn/aredn_ar71xx#280]
Loaded aredn-465-f062021-ubnt-nano-m-xw-sysupgrade.bin on a test NSM5 XW.
Rebooted fine, but unable to load UI on browser - times out.  I  can ssh into system,and verified with nmap that uhttpd is listening on port 8080.   Power-cycling node results in no change.
How to troubleshoot/recover?
Thanks.

**Comment by k1ky** [comment]
Did you try connecting on the other port?

    On Friday, November 23, 2018, 3:52:58 PM CST, Orv <notifications@github.com> wrote:  
 
 
Loaded aredn-465-f062021-ubnt-nano-m-xw-sysupgrade.bin on a test NSM5 XW.
Rebooted fine, but unable to load UI on browser - times out. I can ssh into system,and verified with nmap that uhttpd is listening on port 8080.
How to troubleshoot/recover?
Thanks.

**Comment by Orv** [comment]
Right after I posted this, a second power cycle was successful :-/   Let's close this for now; I'll keep an eye on it.

**Comment by dman776** [comment]
Can you restart the web server?

/etc/init.d/uhttpd restart

Thanks,
Darryl

**Comment by Orv** [comment]
I upgraded this node to aredn-471-2d5beb2-ubnt-nano-m-xw-sysupgrade.bin and rebooted it.  Same behavior: unresponsive UI.
Restarted the web server with /etc/init.d/uhttpd restart.  Same behavior - no web page returned. (verified it was listening on port 8080 with nmap).
Restarted uttpd AGAIN, and now UI responds.  Will continue watching node.

**Comment by ae6xe** [comment]
I can reproduce.  Nothing I do is enabling the UI to work.  hmmm..   Anything in logread output related to httpd on your node?

**Comment by ae6xe** [comment]
addressed in successive builds. reverted a change to uhttpd.

https://github.com/aredn/aredn_ar71xx/commit/557e4b3903ae0c320abce02557b42a9b1fdadf86
https://github.com/aredn/aredn_ar71xx/commit/483b138b3a7d76318ba9a934b294317fbd32e7b5
