### ISSUE TITLE
Non-persistant poe power setting on hAP AC lite build aredn-485

### ISSUE THREAD

**Issue by AC0WN** [aredn/aredn_ar71xx#284]
After installing aredn-485-a59fe25-mikrotik-rb-nor-flash-16M-ac-sysupgrade.bin on a MikroTik hAP AC lite it appears setting poe OFF on the DtD port is not persistant.  After each reboot the DtD port is powered and displaying the red light.  I was careful to use the "Save" button prior to each reboot.

Someone please tell me if I have reported this properly and in the correct location.

julie  /ac0wn

**Comment by ae6xe** [comment]
julie,  check carefully about 30 seconds or so after power on.   The POE is 'on' while the device is booting.  Then this setting will take effect and it will be turned off.   The hardware will check for proper load, and if not in operating range, the power will not be supplied--light will turn green if connected to, e.g. a netgear switch.  Does this explain the situation you are seeing?

**Comment by AC0WN** [comment]
Joe - thank you for your comments - here is what I am seeing:

With build aredn-485-a59fe25-mikrotik-rb-nor-flash-16M-ac-sysupgrade.bin:
I put a Ubiquiti NanoBeam M5-19 on the DtD port and a volt / current pass thru meter with an android phone attached to give the usb port some load.  I reboot the hAP AC lite and it comes up with poe hot on the DtD port and the USB port is cold (zero volts / amps).  Going into the advanced configuration page both the poe and the usb ports are selected as ON and the boxes are blue.  As soon as I click on the SAVE button of the USB port the usb port than goes hot and shows 5 vdc and about .35 amp charging the phone.  I then deselect the poe box and click on it's SAVE button.  This shuts off poe on the DtD port and the box is unchecked and now labeled OFF, and the red light on the DtD port goes out.  From here I try two different tests:

Test one:  Click on the reboot button on the advanced configuration page.
Test two:  Go directly to basic setting page, click on save changes, click on reboot.

Result in both cases is the same.  When the router reboots it comes up same as before the test with poe hot on the DtD port and the USB port cold.

I then updated the hAP AC lite with this build:  aredn-491-a62fe95-mikrotik-rb-nor-flash-16M-ac-sysupgrade.bin

Ran all the same tests with the same results.

**Comment by ae6xe** [comment]
I believe this issue was resolved by this fix:  https://github.com/aredn/aredn_ar71xx/commit/86ec92ac46b3cf78a4b447593c17083940ec0b2b 
and is later nighly builds.   There was a typo on the USB code, was calling POE incorrectly, so USB settings were never changed.   I'll go ahead and close this.
