### ISSUE TITLE
cpe 210v2 device always give warning when uploading firmware

### ISSUE THREAD

**Issue by ae6xe** [aredn/aredn_ar71xx#290]
![image](https://user-images.githubusercontent.com/25602681/49199007-bd11f400-f34a-11e8-8756-f72f716b19cb.png)

get_boardid:  TP-Link CPE210 v2.0
get_hardwaretype: cpe210-v2
get_hardware_mfg:  TP-Link CPE210 v2.0
get_model: TP-Link CPE210 v2.0

**Comment by raysuelzer** [comment]
Can you go to admin page, right click view source and see what the search string is that it is trying to use? I've been looking at this for a bit, but it seems like if the details you posted are correct that it should be setting the hardware type correctly in the search string.

**Comment by ae6xe** [comment]
the hwtype is not getting setup from the perl script:

    <script>
    function validateFirmwareFilename(elem){
        var hwtype = "";
        var searchstring = ".*-" + hwtype + "-sysupgrade.bin";
        var re = new RegExp(searchstring,"g");   
        if(elem.value.match(re)){
            return true;
        }else{
            if (confirm('This filename is NOT appropriate for this device!\n\nThis device expects a file such as: aredn-3.18.9.0-cpe--sysupgrade.bin\n\n\nClick OK to continue if you are CERTAIN that the file is correct.')) {
                return true;
            } else {
                elem.value="";
                return false;
            }
        }
    }
    </script>

**Comment by raysuelzer** [comment]
It looks like your script is different from mine as it does not do a CPE check. I wonder what else is different?

`  <script>
    function validateFirmwareFilename(elem){
        var hwmfg = "mikrotik";
        var hwtype = "rb-nor-flash-16M-ac";
        var searchstring = "";
        var efn = "";
        if(hwmfg != "cpe"){
            searchstring= ".*-" + hwtype + "-sysupgrade.bin";
            efn = "aredn-491-a62fe95-mikrotik-rb-nor-flash-16M-ac-sysupgrade.bin";
        } else {
            searchstring= ".*cpe" + hwtype + "-sysupgrade.bin";
            efn = "aredn-491-a62fe95-mikrotikrb-nor-flash-16M-ac-sysupgrade.bin";
        }
        var re = new RegExp(searchstring,"g");   
        if(elem.value.match(re)){
            return true;
        }else{
            if (confirm('This filename is NOT appropriate for this device!\n\nThis device expects a file such as: ' + efn + ' \n\n\nClick OK to continue if you are CERTAIN that the file is correct.')) {
                return true;
            } else {
                elem.value="";
                return false;
            }
        }
    }
    </script>`

**Comment by dman776** [comment]
on a CPE510 v1.0, it is correct.   the response is:
.....
<script>
    function validateFirmwareFilename(elem){
        var hwmfg = "cpe";
        var hwtype = "510-520-v1";
        var searchstring = "";
        var efn = "";
.....
