### ISSUE TITLE
Mikrotik - enabling LAN Access point disables Mesh WAN access

### ISSUE THREAD

**Issue by Orv** [aredn/aredn_ar71xx#298]
On nightly build 509-303c509 on the Mikrotik 952Ui-5ac2nD, enabling the 5 GHz LAN access point disables mesh LAN access, even when "Allow others to use my WAN" is checked.
Disabling the LAN access point allows remote nodes to access the Internet through the Mikrotik again.

Support data file is attached (renamed .gz in order to allow upload).  (this is with the 5 GHz AP enabled).

[supportdata-W6BI-Shack-Node-201812010112.gz](https://github.com/aredn/aredn_ar71xx/files/2641977/supportdata-W6BI-Shack-Node-201812010112.gz) (NOTE - date is incorrect on node; this support data file was created today).

 
--

**Comment by dman776** [comment]
Confused.  Did you mean that it disables mesh WAN access?

**Comment by Orv** [comment]
Yes.

**Comment by ae6xe** [comment]
I went to reproduce this and suddenly my hAP lite doesn't boot...  It may be a few days before I can look at this and hopefully I don't need to get another one :) .     To confirm the test to reproduce:

1)  in basic settings, check the box "Allow others to use my WAN".   
2)  in basic settings, check the box under LAN Access Point, "enable". 
3) Save settings and reboot
4) test the remote users across the mesh (not the local LAN devices) can access the internet though this's nodes WAN gateway.
5) in basic settings, uncheck  the box under LAN Access Point, "enable"
6) Save settings and reboot
7)  repeat step #4. 

One of step 4 or 7 will fail and one will succeed?

**Comment by Orv** [comment]
In my experience, with 1 and 2 set, 4 will fail.

**Comment by ae6xe** [comment]
Orv,   I installed build 516 and initialized settings with step 1, 2, and 3.    NSM2 -> 2GHz link -> hAP -> WAN link to home network.    While telnet into the NSM2, I can ping and traceroute to confirm the routing is though the hAP to the internet.    

could this be a 12v vs 24v issue?  Failures of various symptoms have been observed when running 12v on the hAP ac lite.  The stability is suspect.  re-test on your end with a 24v ps, unless already there.

**Comment by Orv** [comment]
Joe, I don't have access to 516 any more.  My Mikrotik is running 522.
I'm running the provided 24 V wallwart so that's probably not an issue.
I have NSM5 (mesh network) NSM5 -> hAP (via DtD) -> WAN link to home network.  This works fine if the 5 GHz AP isn't enabled.  When it's enabled, not so much.
I'll test more later tonight.

**Comment by ae6xe** [comment]
I was able to ping the internet from the NSM2:      NSM2 ->DTDLink -> hAP -> WAN to internet .  I'm still running 516.  I'll reload with latest nightly and try again tomorrow.

**Comment by dman776** [comment]
I tested this with build 522 and cannot replicate.

NSM5XW main port to POE, POE LAN port to DTD on switch to rest of the mesh
NSM5XW secondary port to hAP AC Lite "POE In" port
enabled POE Passthru on NSM5XW
hAP AC Lite booted fine with a WAN address of the NSM5XW
enabled AP mode on the hAP Lite and rebooted
hAP AC Lite booted fine with a WAN address of the NSM5XW
Connected laptop to AP wifi.
browsed internet successfully; Upload Data to AREDN Servers successful.

**Comment by ae6xe** [comment]
Orv,  telnet to the NSM5 at the very end of the hops from the hAP AC lite,  what does "traceroute www.google.com" return?

**Comment by Orv** [comment]
Just to clarify - which image should be loaded?  ac- or non-ac?

**Comment by ae6xe** [comment]
The 5GHz is 802.11ac,    thus need the "ac"  image with the ath10k driver.

**Comment by Orv** [comment]
I must have the ac version installed then, as when I test the AP it 
worked properly.

I'll test more after work this afternoon.

Orv

**Comment by Orv** [comment]
Guys, after upgrading to the very latest -ac version, I'm unable to reproduce this issue.   We can close it.  Sorry to take up precious dev bandwidth.
Orv

**Comment by dman776** [comment]
Closing at the request of the reportee
