### ISSUE TITLE
sysinfo.json File Becomes Unreachable in Non-Mesh RF Mode

### ISSUE THREAD

**Issue by n2mh** [aredn/aredn_ar71xx#317]
When a node is in non-Mesh RF mode (no AP or with AP), the node throws an error when queried for the sysinfo.json file from /cgi-bin/sysinfo.json. This is the error

**Bad Gateway**
The process did not produce any response

This behavior has been seen on a hAP Lite running Nightly 556 and 3 different AirRouters running nightly 566. As soon as the node is back to Mesh on RF, sysinfo.json is available again.

**Comment by ae6xe** [comment]
Commit submitted and adds new meshrf status field:

  "meshrf": {
     "status": "off"
   },

   "meshrf": {
     "status": "on",
     "chanbw": "10",
     "ssid": "AREDN-10-v3",
     "channel": "-2"
