### ISSUE TITLE
Minor GUI Display Issue

### ISSUE THREAD

**Issue by Orv** [aredn/aredn_ar71xx#319]
Using Internet Explorer 11, there's a blue rectangle around the AREDN logo on the firmware status page.

Using Firefox version 64.0 on both Windows 10 and Fedora Linux and Google Chrome 71.0.3578.98 on Linux, that blue rectangle is absent.

**Comment by ae6xe** [comment]
We can add something like this to the html-css code to prevent this:  style=”border-style: none .

**Comment by dman776** [comment]
Orv, can you try this css change (I don't have IE 11).
edit /www/aredn.css
change this line:
.AREDNLogo { background:rgb(231,231,231);  position:absolute; left:10%; width:175; height:95; }
to read:
.AREDNLogo { background:rgb(231,231,231);  position:absolute; left:10%; width:175; height:95; border-style: none;}

**Comment by ae6xe** [comment]
I added this change.   started IE 11, cleared browser cache for everything.  browsed to the status page and did not see the blue rectangle box anymore.

**Comment by Orv** [comment]
For me, this change resolves the issue with IE 11, for both URLs Joe mentioned.
NOTE - I only saw the blue rectangle on my Mikrotik HAP ac Lite; it does not appear on any of my Ubiquiti devices.

**Comment by ae6xe** [comment]
Orv, do you want to confirm this was resolved before we close this one?  Fix was submitted and in build a while back.

**Comment by Orv** [comment]
Soon - still traveling.

**Comment by Orv** [comment]
It appears to be resolved, and may be closed.
