### ISSUE TITLE
Nanostation M5 XW bogus filename warning when upgrading

### ISSUE THREAD

**Issue by Orv** [aredn/aredn_ar71xx#330]
Updating NSM5XW from nightly build 620 to nightly build 636, and got this:
----------------------
This filename is NOT appropriate for this device!
This device expects a file such as: aredn-620-13a6afb-ubnt-nanostation-m-xw-sysupgrade.bin 
Click OK to continue if you are CERTAIN that the file is correct.
--------------------
I thought this issue was resolved?

**Comment by ae6xe** [comment]
this looks like a combination not yet accounted for.   there is no "nanostation-m-xw" named firmware, it is "nano-m-xw".
