### ISSUE TITLE
Another Typo in additional terms of license on website

### ISSUE THREAD

**Issue by jamespbryan** [aredn/aredn_ar71xx#334]
Hello,

This is not a code issue, but the typo might appear in other areas and certainly in downstream projects. On the site:
https://www.arednmesh.org/content/ui-license
the line below should likely be changed. Recommended changes are in bold:

ORIGINAL

> The AREDN™ trademark and AREDN™ logo **and** for use in official Amateur Radio Emergency Data Network (AREDN™) sanctioned builds.

RECOMMENDED

> The AREDN™ trademark and AREDN™ logo for use in official Amateur Radio Emergency Data Network (AREDN™) sanctioned builds.

**The summarized change is the removal of the word "and".

Thanks!

**Comment by wu2s** [comment]
Thank you for catching this.

**Comment by wu2s** [comment]
The recommended change is approved.

**Comment by ae6xe** [comment]
web site is updated.
