### ISSUE TITLE
Add olsr watchdog 

### ISSUE THREAD

**Issue by ae6xe** [aredn/aredn_ar71xx#338]
If olsr locks up or blocks for any reason, the node would not be reachable over the mesh.  Currently, olsr is only restarted if the process no longer exists.  This request is to add a safety net to restart olsr if it is still running, but not processing events.   If such an unexpected event happens, olsr would be restarted, and mesh nodes at hard to access tower sites would still be reachable,

**Comment by k1ky** [comment]
Thank you thank you thank you!
