### ISSUE TITLE
NanoBeam Untested Hardware issue 358 - no change

### ISSUE THREAD

**Issue by rfgarvey** [aredn/aredn_ar71xx#360]
I downloaded and flashed last nights build. There is no change.
The file I am using is: aredn-692-bb818a9-ubnt-loco-m-xw-factory.bin

[n3kal-nanobeam-untested-1.pdf](https://github.com/aredn/aredn_ar71xx/files/2845406/n3kal-nanobeam-untested-1.pdf)
[n3kal-nanobeam-untested-2.pdf](https://github.com/aredn/aredn_ar71xx/files/2845407/n3kal-nanobeam-untested-2.pdf)

[supportdata-N3KAL-NanoBeam.zip](https://github.com/aredn/aredn_ar71xx/files/2845409/supportdata-N3KAL-NanoBeam.zip)

**Comment by ae6xe** [comment]
OK, one more change will be needed.  1 step forward, should be just one more to go.   We may need to do a couple of iterations offline.  Can you email me at ae6xe at arrl dot net (so I have an address to reply to)?  I'm traveling today, so this weekend.

**Comment by rfgarvey** [comment]
Thanks you Joe ae6xe for taking care of this!!

**Comment by ae6xe** [comment]
change had been successful.  Build failed on CircleCI nightly build due to other reasons and was addressed.   Used too many parallel cpu's, and sometimes Openwrt builds don't complete and have to be run with less cpu's, due to timing and dependencies getting out of order.
