### ISSUE TITLE
Minor typo in 3.19.3.0 release notes

### ISSUE THREAD

**Issue by Orv** [aredn/aredn_ar71xx#385]
Minor typo in "AREDN Release Notes v3.19.3.0 – 23 March 2019"

Is:  A new feature adds sounds, including pitch and volume control, to the real-time SNR chart page. As a device is tilted or rotated towards a remote node, the computer generated tone changes pitch based on a higher of lower SNR. This feature assists in aiming a node by indicating a better signal with a higher tone.

Should be:   A new feature adds sounds, including pitch and volume control, to the real-time SNR chart page. As a device is tilted or rotated towards a remote node, the computer generated tone changes pitch based on a higher **or** lower SNR. This feature assists in aiming a node by indicating a better signal with a higher tone.

**Comment by dman776** [comment]
corrected.  thank you.

**Comment by Orv** [comment]
You're very welcome. Great work, guys!
