### ISSUE TITLE
Delete non-existant ssh key kills dropbear 

### ISSUE THREAD

**Issue by ke4ahr** [aredn/aredn_ar71xx#397]
Login to the admin pages, hit the button to select a ssh public key, select a key... then hit the button to delete the key instead.

Kills dropbear, any existing ssh session, disrupts vtun connections. Repeatable, affects both current and previous releases.

current version: 3.19.3.0 hardware type: ubnt (bullet-m)

**Comment by dman776** [comment]
Can you record your screen (video) and link or upload it here?  I can't seem to replicate this.

**Comment by ke4ahr** [comment]
Try using Firefox instead of Chrome. I will see if I can capture the queries with a proxy.

**Comment by dman776** [comment]
I was testing on Firefox 66.0.3 (64-bit) for OSX.

**Comment by r1de** [comment]
I could not recreate this either.  
Using Firefox on Linux.  

I did have my ssh session terminated when I reuploaded my cert (after testing this and deleting it), but there were no other disruptions other than that.

**Comment by dman776** [comment]
closing.   not able to replicate and no additional info from reportee.
