### ISSUE TITLE
Option to allow auto-reboot during package install

### ISSUE THREAD

**Issue by BKasin** [aredn/aredn_ar71xx#400]
Some packages that require a reboot after install, such as the tunnel server, will finish the install and exit with a "Please reboot" message. It could be worth it to have a toggle-able UI option to allow for automatically rebooting when that is the exit status.

**Comment by ae6xe** [comment]
Would prefer to fix specific packages that don't do the right thing.  Individual packages should control the necessary steps for the functionality to work after package install. This may be restarting services or a reboot.  Openwrt design is that all changes do not require a reboot.    Please re-submit for specific packages that do not have the correct behavior.
