### ISSUE TITLE
Update TP-Link network switch config

### ISSUE THREAD

**Issue by Orv** [aredn/aredn_ar71xx#427]
Update code for TP-Link products so the internal switch behaves the same as the Ubiquiti products, i.e., convert to dumb non-VLAN switch.   (appears not to have been done yet)

**Comment by ae6xe** [comment]
The models in scope are the following:  CPE210v1.0, CPE210v1.1,  CPE510v1.0, and CPE510v1.1.  Other newer versions of the TPLink devices only have 1 physical port.  (These older models would not be received if purchased new today, rather only available on used market.)

**Comment by Orv** [comment]
So - no update planned?  Or?

**Comment by ae6xe** [comment]
In queue.  If all models were affected it would be higher in queue.

**Comment by Orv** [comment]
Good to know - thanks.

**Comment by AA7AU** [comment]
> The models in scope are the following: CPE210v1.0, CPE210v1.1, CPE510v1.0, and CPE510v1.1. 

Don't forget my lonely CPE220v3. Thanks for keeping this topic at least somewhat alive.

- Don - AA7AU

**Comment by apcameron** [comment]
PR #523 should address this

**Comment by Orv** [comment]
I'll test in the next day or so.  Thanks, guys.
Orv W6BI

**Comment by apcameron** [comment]
OK, Please wait until the PR has been approved.

**Comment by Orv** [comment]
Of course :-)

**Comment by apcameron** [comment]
This should be ready for testing now in the nightly build.

**Comment by ae6xe** [comment]
https://github.com/aredn/aredn_ar71xx/pull/523#issuecomment-621347799
