### ISSUE TITLE
Update Support Matrix, marking older devices as not recommended for purchase

### ISSUE THREAD

**Issue by Orv** [aredn/aredn_ar71xx#438]
Recommend flagging those devices currently supported by AREDN firmware but not recommended for future purchase, in a different color (red maybe), and add a note to that effect to the existing notes.

**Comment by ae6xe** [comment]
This includes SISO devices and 32M RAM devices, except NS M3 devices where there are no alternatives in same class.

**Comment by dman776** [comment]
done
