### ISSUE TITLE
nightly build filename excessively long.

### ISSUE THREAD

**Issue by Orv** [aredn/aredn_ar71xx#44]
I mean, really??
 AREDN-aredn-develop-10-develop-53cbaf4-r7122-b84a07b-ubnt-nano-m-xw-sysupgrade.bin

**Comment by ae6xe** [comment]
work in progress, give it some time.

**Comment by dman776** [comment]
yes.  currently, you can translate the above filename to:
- it was built from the github.com/**aredn** project
- built from the **develop** branch
- continuous integration build number 10
- commit id 53cbaf4
- etc...

we will refine.

**Comment by ae6xe** [comment]
updates committed:  0f4eeef, will close this issue.
