### ISSUE TITLE
shellcheck test errors during build

### ISSUE THREAD

**Issue by dman776** [aredn/aredn_ar71xx#45]
shellcheck -x is not a valid option

**Comment by ae6xe** [comment]
it is a valid option on current versions of shellcheck 0.4.7.    This was the issue where the docker container came with this upgrade but most distributions of linux do not (and it is difficult to upgrade, having to compile from source).

**Comment by dman776** [comment]
AE6XE will revert the commits that added -x

**Comment by ae6xe** [comment]
fix committed to repo:  ec4bf4e .

Closing this issue.
