### ISSUE TITLE
Add support for Ubiquiti Nanobeam M5 19 (Atheros AR934x)

### ISSUE THREAD

**Issue by radar27** [aredn/aredn_ar71xx#456]
There appears to be at least one additional hardware revision for the Ubiquiti Nanobeam M5 19.  In purchasing two lots on the used market, a batch with the System type: Atheros AR934x exhibited inconsistent behavior on the wired Ethernet port using both the current stable (3.19.3.0 / ubnt-loco-m-xw) as well as snapshot as of 10/1/19 (aredn-1138-6e19994-ubnt-loco-m-xw-factory.bin)

The wired network connectivity seems to be hit or miss for the untagged user traffic and seemingly unidirectional for VLAN2/dtdlink traffic.  Directly wired to test computer sporadically assigns an IP address with DHCP enabled.  When paired with a Ubiquiti Rocket M2 Ti through an unmanaged Ubiquiti Nanoswitch, the dtd connection displays LQ of 100% but NLQ of 0%, as if the Ethernet connection is somehow functioning in one direction.  This system briefly began passing dtd traffic after 36+ hours of being powered up at an unattended location.  Once the Nanobeam M5 19 was reset after trying a second Nanoswitch, the original behavior of "one way" dtd traffic resumed.

The wireless side seems to work just fine, held a fairly solid link 19 miles to another Nanobeam M5 19 with the "Atheros AR9342 rev 2" System type and suggested ubnt-loco-m-xw stable image.

This appears to have the same processor type as the TP-Link CPE610 as noted in issue [#219](https://github.com/aredn/aredn_ar71xx/issues/219).  This may be similar to the November 2017 test date issue on the Nanostation Loco M5.  I did attempt loading the aredn-3.19.3.0-ubnt-rocket-m-xw-factory.bin for the after November 2017 issue as well as the aredn-3.19.3.0-ubnt-nano-m-xw-factory.bin, just to test out all available XW firmware.  Unfortunately no other firmware seemed to provide usable wired ethernet, so I am hoping adding support for this version is possible.

Here are system details taken from AirOS XW 6.2.0

**cat /proc/cpuinfo**
system type             : Atheros AR934x
processor               : 0
cpu model               : MIPS 74Kc V4.12
BogoMIPS                : 266.24
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0000, 0x0530, 0x0788, 0x01b8]
ASEs implemented        : mips16 dsp
shadow register sets    : 1
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

**dmesg**
[    0.000000] Linux version 2.6.32.71 (buildd@builder) (gcc version 4.8.3 (OpenWrt/Linaro GCC 4.8-2014.01 r18801) ) #1 Wed Jul 3 11:18:17 EEST 2019
[    0.000000] flash_size passed from bootloader = 8
[    0.000000] CPU revision is: 0001974c (MIPS 74Kc)
[    0.000000] ath_sys_frequency: cpu srif ddr srif cpu 535 ddr 400 ahb 200
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 04000000 @ 00000000 (usable)
[    0.000000] User-defined physical RAM map:
[    0.000000]  memory: 04000000 @ 00000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Zone PFN ranges:
[    0.000000]   Normal   0x00000000 -> 0x00004000
[    0.000000] Movable zone start PFN for each node
[    0.000000] early_node_map[1] active PFN ranges
[    0.000000]     0: 0x00000000 -> 0x00004000
[    0.000000] On node 0 totalpages: 16384
[    0.000000] free_area_init_node: node 0, pgdat 8028a470, node_mem_map 81000000
[    0.000000]   Normal zone: 128 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 16256 pages, LIFO batch:3
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 16256
[    0.000000] Kernel command line: console=tty0 root=31:03 rootfstype=squashfs init=/init mtdparts=ath-nor0:256k(u-boot),64k(u-boot-env),1024k(kernel),6528k(rootfs),256k(cfg),64k(EEPROM) mem=64M panic=3 quiet
[    0.000000] PID hash table entries: 256 (order: -2, 1024 bytes)
[    0.000000] Dentry cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Inode-cache hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
[    0.000000] Writing ErrCtl register=00000000
[    0.000000] Readback ErrCtl register=00000000
[    0.000000] Memory: 61936k/65536k available (2081k kernel code, 3532k reserved, 516k data, 132k init, 0k highmem)
[    0.000000] Hierarchical RCU implementation.
[    0.000000] NR_IRQS:128
[    0.000000] CPU0 IRQ stack at 0x83810000 - 0x83814000
[    0.000000] plat_time_init: plat time init done
[    0.000000] Console: colour dummy device 80x25
[    0.000000] console [tty0] enabled
[    0.000000] Calibrating delay loop... 266.24 BogoMIPS (lpj=133120)
[    0.022000] Mount-cache hash table entries: 512
[    0.024000] NET: Registered protocol family 16
[    0.032000] bio: create slab <bio-0> at 0
[    0.034000] Switching to clocksource MIPS
[    0.036000] NET: Registered protocol family 2
[    0.037000] IP route cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.038000] TCP established hash table entries: 2048 (order: 2, 16384 bytes)
[    0.038000] TCP bind hash table entries: 2048 (order: 1, 8192 bytes)
[    0.038000] TCP: Hash tables configured (established 2048 bind 2048)
[    0.038000] TCP reno registered
[    0.039000] NET: Registered protocol family 1
[    0.039000] ATH GPIOC major 0
[    0.040000] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.041000] msgmni has been set to 121
[    0.041000] io scheduler noop registered (default)
[    0.065000] Serial: 8250/16550 driver, 1 ports, IRQ sharing disabled
[    0.066000] serial8250.0: ttyS0 at MMIO 0xb8020000 (irq = 19) is a 16550A
[    0.067000] 6 cmdlinepart partitions found on MTD device ath-nor0
[    0.067000] Creating 6 MTD partitions on "ath-nor0":
[    0.067000] 0x000000000000-0x000000040000 : "u-boot"
[    0.069000] 0x000000040000-0x000000050000 : "u-boot-env"
[    0.070000] 0x000000050000-0x000000150000 : "kernel"
[    0.071000] 0x000000150000-0x0000007b0000 : "rootfs"
[    0.072000] mtd: partition "rootfs" set to be root filesystem
[    0.072000] 0x0000007b0000-0x0000007f0000 : "cfg"
[    0.073000] 0x0000007f0000-0x000000800000 : "EEPROM"
[    0.074000] u32 classifier
[    0.074000]     Performance counters on
[    0.074000]     input device check on
[    0.074000]     Actions configured
[    0.076000] TCP westwood registered
[    0.076000] NET: Registered protocol family 10
[    0.079000] NET: Registered protocol family 17
[    0.079000] Bridge firewalling registered
[    0.079000] 802.1Q VLAN Support v1.8 Ben Greear <greearb@candelatech.com>
[    0.079000] All bugs added by David S. Miller <davem@redhat.com>
[    0.079000] athwdt_init: Registering WDT success
[    0.080000] Reset: Normal
[    0.080000] ath_otp_init: Registering OTP success
[    0.080000] ath_clksw_init: Registering Clock Switch Interface success
[    0.088000] VFS: Mounted root (squashfs filesystem) readonly on device 31:3.
[    0.089000] Freeing unused kernel memory: 132k freed
[    0.100000] Please be patient, while AirOS loads ...
[    0.787000] Algorithmics/MIPS FPU Emulator v1.5
[    1.298000] ubnthal: module license 'Proprietary' taints kernel.
[    1.299000] Disabling lock debugging due to kernel taint
[    1.342000] ubnthal: initializing...
[    1.342000] ath-gpio 2.0 initialised
[    1.342000] ubnthal: initialised, board found, sysid = 0xe825, name = NanoBeam M5
[    1.342000] ubnthal: host_board_t size: 1400B, boards table size: 41kB, SoC id: 0x1122
[    6.350000] ATHR_GMAC: Length per segment 1536
[    6.350000] ATHR_GMAC: skb_overhead 64, shinfo: 344
[    6.350000] ATHR_GMAC: RX sizes - 2k_fit: 1612, reserve: -2
[    6.350000] ATHR_GMAC: fifo cfg 3 01f00140
[    6.350000] AR8032 Detected
[    6.350000] ATHR_GMAC: Mac address for unit 0:bfff0000
[    6.350000] ATHR_GMAC: 44:d9:e7:b5:77:b2
[    6.905000] MAC0 MDC is 3 at line 2917
[    6.905000] mac:0 Registering S27....
[    6.905000] Configuring GPIO4 GPIO Function.
[    6.905000] Setting GPIO4 to INPUT.
[    6.905000] Setting GPIO15 to INPUT.
[    6.905000] Setting GPIO17 to INPUT.
[    6.905000] ATHR_GMAC: Max segments per packet :   1
[    6.905000] ATHR_GMAC: Max tx descriptor count :   128
[    6.905000] ATHR_GMAC: Max rx descriptor count :   252
[    6.905000] ATHR_GMAC: Mac capability flags    :   4381
[    6.906000] ATHR_GMAC: Mac address for unit 1:bfff0006
[    6.906000] ATHR_GMAC: 46:d9:e7:b5:77:b2
[    7.461000] mac:1 Registering S27....
[    7.461000] ATHR_GMAC: Max segments per packet :   1
[    7.461000] ATHR_GMAC: Max tx descriptor count :   128
[    7.461000] ATHR_GMAC: Max rx descriptor count :   252
[    7.461000] ATHR_GMAC: Mac capability flags    :   4B80
[    7.736000] PPP generic driver version 2.4.2
[   10.413000] PPP MPPE Compression module registered
[   10.442000] NET: Registered protocol family 24
[   10.552000] URD Init
[   11.026000] ath_hal: 0.9.17.1 (AR9380, DEBUG, REGOPS_FUNC, 11D)
[   11.499000] ubnt_ewma_ht loaded
[   12.047000] ath_rate_atheros: Copyright (c) 2001-2005 Atheros Communications, Inc, All Rights Reserved
[   12.483000] ath_dev: Copyright (c) 2001-2007 Atheros Communications, Inc, All Rights Reserved
[   12.989000] ath_ahb: 9.2.0_U11.14 (Atheros/multi-bss)
[   12.989000] __ath_attach: Set global_scn[0]
[   12.989000] ACBKMinfree = 48
[   12.989000] ACBEMinfree = 32
[   12.989000] ACVIMinfree = 16
[   12.989000] ACVOMinfree = 0
[   12.989000] CABMinfree = 48
[   12.989000] UAPSDMinfree = 0
[   12.997000] Bootstrap clock 40MHz
[   13.000000] ar9300Attach: This Mac Chip Rev 0x300.2 PCI devid 0x31
[   13.000000] Wasp Enterprise mode: 0x00000000
[   13.001000] ar9300RadioAttach: Need analog access recipe!!
[   13.026000] Restoring Cal data from Flash
[   13.027000] Using Cal data from Flash 0xbfff1000
[   13.027000] ath_hal: Ubiquiti Osprey (0777:e825)
[   13.027000] ath_hal: DFS Testing disabled.
[   13.027000] Invalid country[0] on locked SKU forcing to default country.
[   13.072000] ath_set_tx: FF mode xmit queue created HWQ=4
[   13.072000] ubnt_ewma_ath_rate_attach: Attach succesful
[   13.079000] ath_get_caps[5755] rx chainmask mismatch actual 3 sc_chainmak 0
[   13.079000] ath_get_caps[5730] tx chainmask mismatch actual 3 sc_chainmak 0
[   13.093000] IRQ 2/wifi0: IRQF_DISABLED is not guaranteed on shared IRQs
[   13.105000] wifi0: Atheros 9340: mem=0xb8100000, irq=2
[   13.495000] ubnt_poll: Initializing polling module...
[   13.495000] ubnt_poll: Initializing packet classifier...
[   13.496000] ubnt_poll: OS timer frequency 1000 Hz
[   13.515000] rssi-leds 1.2 loaded
[   13.695000] ubnt_poll: Attaching hooks...
[   13.700000] wlan_vap_create : enter. devhandle=0x83ac02c0, opmode=IEEE80211_M_STA, flags=0x3
[   13.700000] ubnt_poll: TX CTRL configured with 0/18/200/0/6/0/0
[   13.700000] ubnt_poll: Initializing STA ranging engine
[   13.700000] ubnt_poll_host: Initialized in STA mode for device wifi0
[   13.700000] ubnt_poll_11ac: Initialized
[   13.700000] ubnt_poll_11ac: Configured in STA mode
[   13.701000] ubnt_ewma_ath_rate_create_vap: succesful
[   13.701000] VAP attach: burst beacon mode.
[   13.703000] wlan_vap_create : exit. devhandle=0x83ac02c0, opmode=IEEE80211_M_STA, flags=0x3.
[   13.885000] ubnt_poll_set_noack_rate: was set auto_rate 1 mcs_index 0
[   14.161000] Ebtables v2.0 registered
[   14.695000] device eth0 entered promiscuous mode
[   14.700000] device ath0 entered promiscuous mode
[   14.706000] device eth1 entered promiscuous mode
[   14.737000] ADDRCONF(NETDEV_UP): lo: link is not ready
[   14.737000] ADDRCONF(NETDEV_UP): br0: link is not ready
[   14.753000] athr_gmac_ring_alloc Allocated 2048 at 0x82dc9000
[   14.753000] athr_gmac_ring_alloc Allocated 4032 at 0x82c8c000
[   15.053000] athr_gmac_mii_setup 0
[   15.053000] WASP ----> AR8032 PHY
[   15.053000] MAC0 MDC is 3 at line 643
[   15.053000] Setting Drop CRC Errors, Pause Frames and Length Error frames
[   15.053000] Setting FIFO_CFG_5 to 0x7efff
[   15.053000] Setting PHY...
[   15.053000] Forced AR8032 PHY hardware reset on PHY setup.
[   18.076000] ATH_MAC_TIMER: MAC 0 PHY 0x01 - LINK NOW UP [link=UP speed=100Mbps duplex=full duplex carrier=0]
[   18.087000] ubnt_poll: Setting timing params to min:1000 max:3000 offset:3000 tx_time: 3000 init: 5
[   18.087000] ubnt_poll: Setting aggregation params to non-txop:0 tx-op:0 scheduling:0
[   18.087000] ubnt_poll: Setting TXOP Window parameters to size:25 timeout-perc:5
[   18.087000] ubnt_poll: AR934x CPU Freq set at 535 MHz, using auxillary timer at 40 KHz, ref=40 MHz
[   18.087000] ubnt_poll: Module started in STA mode
[   21.104000] ADDRCONF(NETDEV_UP): ath0: link is not ready
[   21.115000] br0: port 1(eth0) entering learning state
[   22.115000] br0: port 1(eth0) entering forwarding state
[   26.209000] athr_gmac_ring_alloc Allocated 2048 at 0x839a8800
[   26.209000] athr_gmac_ring_alloc Allocated 4032 at 0x82e6c000
[   26.510000] athr_gmac_mii_setup 1
[   26.511000] WASP ----> S27 PHY MDIO
[   26.511000] MAC1 MDC is 3 at line 728
[   26.511000] Setting Drop CRC Errors, Pause Frames and Length Error frames
[   26.511000] ATHRS27: resetting s27
[   26.611000] ATHRS27: s27 reset done
[   26.622000] Setting PHY...
[   27.649000] ADDRCONF(NETDEV_UP): eth1: link is not ready

**cat /etc/board.info**
board.sysid=0xe825
board.cpurevision=0x00001122
board.name=NanoBeam M5
board.shortname=N5B
board.subtype=19
board.netmodes=7
board.hwaddr=44D9E7B477B2
board.reboot=40
board.upgrade=150
board.phycount=1
board.phy.1.maxmtu=2024
board.phy.2.maxmtu=2024
radio.1.name=
radio.1.shortname=
radio.1.bus=ahb
radio.1.devdomain=5000
radio.1.ccode=42
radio.1.ccode_fixed=0
radio.1.ccode_locked=2
radio.1.cap.station_only=1;
radio.1.cap.ap_only=1;
radio.1.subsystemid=0xe825
radio.1.subvendorid=0x0777
radio.1.txpower.max=26
radio.1.txpower.min=-4
radio.1.txpower.offset=4
radio.1.ieee_modes=5
radio.1.antennas=1
radio.1.def_antenna=4
radio.1.antenna.1.id=4
radio.1.antenna.1.name=Built in
radio.1.antenna.1.gain=19
radio.1.antenna.1.builtin=1
radio.1.antenna.1.chains=2
radio.1.antenna.1.chain.1.id=0
radio.1.antenna.1.chain.1.name=Horizontal
radio.1.antenna.1.chain.2.id=1
radio.1.antenna.1.chain.2.name=Vertical
radio.1.distance_limit_km=0
radio.1.chanbw="5,8,10,20,30,40"
feature.rssi.leds=4
feature.ext_reset=0

**Comment by ae6xe** [comment]
Can you load AREDN and work to access over the network port, then capture the support data download file (over RF if necessary through another node)?    The symptoms on the network port, since it is intermittent, suggests there might be a hardware issue.    There may be messages in the system logs of the network interface to give more information, I'd be looking for the interface going down/up repeatedly.  Generally, if there is a new hardware rev, then it ether works or it doesn't.

**Comment by radar27** [comment]
Thanks for the prompt reply.  I too had originally thought it was hardware, I had a second Nanobeam M5 19 at the same location targeting a secondary 5 GHz link which was exhibiting similar behavior.  The interconnecting cables were tested before and after and showed continuity/order between all 8 pins and shield.  In the troubleshooting process, we replaced both the Nanoswitch and new tested cables and the behaviors persisted.  Attached is the support bundle for the AR934x in question (the .tgz was renamed to zip to allow upload).  

[supportdata-NOCALL-201901301222.zip](https://github.com/aredn/aredn_ar71xx/files/3679329/supportdata-NOCALL-201901301222.zip)

One other piece to this puzzle is that I reflashed this unit with the native AirOS 6.2.0 XW, connected to a local part 15 AP and was able to push approximately 35 megabit to an Internet speed test site through it in standard bridging mode (Laptop -> Nanobeam M5 19 -> Bullet M5 -> Firewall -> Internet).  This led me to believe the unit hardware was operating correctly.  I also tried moving the unit around from being directly into a laptop (via PoE injector) and also through an 10/100 unmanaged switch and discovered that changing between connections was resulting in intermittent connectivity even with AirOS.  

Lastly, in my subsequent testing, I also discovered that AirOS was reporting a different system type than the AREDN firmware on the same unit. 

XW.v6.2.0# cat /proc/cpuinfo
system type             : Atheros AR934x
processor               : 0
cpu model               : MIPS 74Kc V4.12
BogoMIPS                : 266.24

root@NOCALL:~# cat /proc/cpuinfo
system type             : Atheros AR9342 rev 2
machine                 : Ubiquiti Loco M XW
processor               : 0
cpu model               : MIPS 74Kc V4.12
BogoMIPS                : 266.64

Given all this, I think my correlation between the reported system type is not likely at fault here.  I am going to close this off and do more testing with the other units and combinations of switches/devices.  I apologize for misidentifying the issue, I now agree that this is most likely faulty hardware, though it's behavior has left me puzzled.  If I do uncover something consistent that can be reproduced on multiple units I'll be sure to check back in.  Thanks for all your excellent work!

**Comment by ampledata** [comment]
@radar27 I'm committing the royal sin of commenting on a closed issue, but I wanted to let you know that in the lot of NanoBeam M5-19s I've received, I've had at least 2 units exhibit the behavior you've described (I have several more left to test...)
