### ISSUE TITLE
services are not publishing

### ISSUE THREAD

**Issue by jeffgus** [aredn/aredn_ar71xx#494]
build 1409-7243fe0
Ubiquiti Nanostation M (XW)

If I try to publish services for hosts other than the node itself, the services will not appear. 

I cleared, rebooted, and then re-added the services with no success. The services are written to the config file, but never how up under the mesh status.

**Comment by ae6xe** [comment]
attach a support download file.  Click link at bottom of Administration page.

**Comment by jeffgus** [comment]
I suspected it was something I was messing around with on the file system. I thought I undid my adhoc changes, but nope! I found the issue and it now works.

Everything looks good now.
