### ISSUE TITLE
Ability to "hide" local hosts on Mesh Status page

### ISSUE THREAD

**Issue by k6ccc** [aredn/aredn_ar71xx#508]
I am suggesting a way to hide local services so that they do not appear on the Mesh Status page.  Here are a couple screen captures from my hAP at home that will explain this better.  First the DHCP reservations.  I have reservations for five WiFi gateways on my home WiFi network.  Currently that VLAN is not connected to any of the APs  Therefore, those IPs are not even in use - but there are reservations.  And therefore, they appear on the Mesh Status page.  Even if they were connected, there is zero reason for them to show up.
http://k6ccc.org/aredn/AREDN_DHCP-Res_page.png
http://k6ccc.org/aredn/AREDN_Local-hosts_page.png
My suggestion would be to add a checkbox for each reservation that hides that item from the Mesh Status page.  Additionally, add a checkbox that hides any attached device that has a DHCP
lease that does not have a reservation.  For example, if I plug my laptop into a node, there is generally no need for that laptop to show up on the Mesh Status page.
This would give the advantage to shortening the Mesh Status page to only useful information.
This is some related to issue #376

**Comment by ae6xe** [comment]
Do you want these hostnames with DHCP reservations to be distributed across the mesh?  Thus, you can access the host remotely knowing the hostname.   Note, if the hostname is advertised across the mesh, mesh status would need some flag to know not to display -- a dilemma on how how OLSR would propagate such a flag.

**Comment by k6ccc** [comment]
At least in my case, I would have no reason for the information to be advertised in any way.  Obviously if it's an advertised service, there would be little reason to hide it.  
Simple answer, if the hide checkbox is checked, OLSR does not distribute it.

**Comment by Blupanthr2** [comment]
I would like to request this too.  I have a proxmox server and a static IP set for it, but I don't want it advertised on the mesh, only the virtuals that it serves.

**Comment by r1de** [comment]
I think I figured out how to do this.  
So far it is working, I have a DHCP lease, I can resolve it locally _on that node_, and I can see it in the mesh list still _on that node_, but the name is no longer propagating over the rest of the mesh.  

Getting this into the GUI is a whole 'nother thing (for me at least).

Messing around with #516 (and the discussion in #538 ) gave me the idea for this issue.

**Comment by r1de** [comment]
My idea for this is to have a checkbox on each DHCP lease allow the user to choose "Do not propagate this name over the mesh" or not.  
We'd just need to add a comment on the lease line in `/etc/ethers` when the lease is saved _and_ the box is checked, something like "#NOPROP".  
The line in `/etc/ethers` would now look like: `aa:bb:cc:dd:ee:ff 10.x.x.x #NOPROP`  
  
_Then_ in `/usr/local/bin/olsrd-config` we just do this:
```
if(-f "/etc/config/dmz-mode")
{
  #($lanip, $lanmask, $lanbcast, $lannet) = get_ip4_network("eth0.0");
  foreach(`cat /etc/ethers`)
  {
    ($junk, $junk, $noprop) = split ' ', $_;
    next if $noprop eq "#NOPROP";
...
```  
  
I am sure there is a much more elegant way of doing it, but that's what I came up with to check if it worked. (it _does_! :) )
  
I am still having "GUI coding block" so I am not sure when I can get this done. sorry all!

**Comment by r1de** [comment]
I got over my writers block, at least for today.
Standby for upcoming PR for this issue! :tada:
