### ISSUE TITLE
Enhancement Request:  Add DNS Aliases

### ISSUE THREAD

**Issue by AG7GN** [aredn/aredn_ar71xx#516]
Add the ability to make DNS aliases configured on a node be resolvable on nodes throughout the mesh.  With this feature, the same DHCP (or even static IP) host on an a node's LAN can be reached by names other than the host's hostname.  The DNS aliases should also be available as a dropdown when making services.

Example:  I have a Linux web server on my node's LAN.  I'd like to set up virtual servers for different purposes on that web server, each with it's own name.  The virtual server's name would have a DNS alias I'd configure on my node, and then those aliases would be resolvable on any other node on the mesh and be visible as a service on the other nodes.

Thank you,

Steve
AG7GN

**Comment by solutionnuts** [comment]
This would be amazing!! Would ultimately streamline and make things more manageable.

**Comment by AG7GN** [comment]
Just tried it using the nightly build and it works.  I look forward to having the aliases available in the Advertised Services URL dropdown so others on the mesh can see them.  Thanks!

Steve
AG7GN

**Comment by AG7GN** [comment]
#516
@r1de On closer examination, I see that it is not working.  Has the partial implementation of the enhancement you mentioned earlier in this thread been rolled into the nightly builds?  I don't see the changes in /usr/local/bin/olsrd-config or /etc/arednsysupgrade.conf in the June 7 2020 build.

Steve
AG7GN

**Comment by r1de** [comment]
no part of this is in the firmware yet.
I am having coders block with the GUI portion.

Adding the ability for OLSR to do this is trivial, but will require the user to edit a text file or 2, by hand, with the command line... :exploding_head:

**Comment by AG7GN** [comment]
@r1de Suggestion:  How about a dropdown pick list containing all possible IP addresses for hosts on the LAN subnet and then underneath that, a table of 2 columns and, say, 5 rows.  The first column is a check box the second is a text field.  For the IP address selected in the dropdown, you'd enter up to 5 aliases, one in each of the text fields.  The checkbox would be used to delete an alias.  

Steve
AG7GN

**Comment by r1de** [comment]
too confusing (IMO).  
As it is right now (for my testing), it looks like this:  
![aliases](https://user-images.githubusercontent.com/4380477/85934812-50036f00-b89d-11ea-8177-303481c850b3.png)
it'll just be a 2 choices, user input of hostname and a drop down of IP's that already have leases...
Not sure if you will be able to create an alias for _any_ available LAN IP though... I am not sure it'll work that way, maybe it will.  
Once I can get the GUI to work right I might be able to test that!!  :confounded:

**Comment by AG7GN** [comment]
Good progress!  Thanks for the update.  Will you limit the number of aliases one can assign to the same IP address?

Steve

**Comment by r1de** [comment]
> Will you limit the number of aliases one can assign to the same IP address?  
  
No. There is no limit.
You will be able to make aliases for DHCP leased hosts as well as for any other _non-leased_ IP's, though one does have to keep in mind that the non-leased IP's may or may not change and will have to be updated.  
  
Also, one should be able to create services based on these aliased host names! Virtual Servers here we come!

Do not get too excited yet tho, this is still a WIP.

**Comment by r1de** [comment]
Had to get the aliased services to work properly, also had to add the aliases to the proper file so they would show up on the localnodes mesh status listing.  
You can't manage what you can't see! :smile:  
  
PR forthcoming after some more testing to make sure it's working.

**Comment by r1de** [comment]
"test-alias" and "kg6wxc-mail" are both aliases, and you can see they show up normally.
The rest of the network see's them as normal hosts as well.
![alias_listings](https://user-images.githubusercontent.com/4380477/92422912-f5578080-f133-11ea-81c1-9724bd42a9c2.png)
(ignore the "greyed out" names, I wont give anything away, but you might figure it out based on the other image, that change will be coming in a little bit!)

Here is what my ports page looks like now with the aliases:
![ports_page](https://user-images.githubusercontent.com/4380477/92423005-42d3ed80-f134-11ea-93a8-f567d3d9a548.png)
  
All testing so far has been positive, lets hope it stays that way! :tada:
