### ISSUE TITLE
Node shows as (tun) but is not configured as such.

### ISSUE THREAD

**Issue by ai6bx** [aredn/aredn_ar71xx#520]
AI6BX-1-RM5-XW-Elsinore, 10.86.10.249, should show up  as a dtd with the remaining -1 nodes at this site however since upgrading it shows as (tun). Additionally, when looking at it in the ETX list it will show as (tun*1). I have tried reboots and OLSR restarts with no change. Any ideas?

Keith - AI6BX

**Comment by Orv** [comment]
I've seen this behavior also.
Orv W6BI

**Comment by ae6xe** [comment]
Keith, I restarted OLSR on AIBX-1-RM5-XW-Elsinore and it shows correctly now on the neighbor's mesh status.    Were you restarting OLSR on this node?    I confirmed this node was not propagating its "dtdlink.ai6bx-1-rm5-xw-elsinore" interface/hostname.    it is a duplicate of https://github.com/aredn/aredn_ar71xx/issues/431 .

**Comment by Orv** [comment]
![image](https://user-images.githubusercontent.com/1124405/80165617-96340d80-8590-11ea-89f0-347315c0f9cf.png)

**Comment by Orv** [comment]
These are Dtd links at the West LA VA.

![image](https://user-images.githubusercontent.com/1124405/80165679-c4b1e880-8590-11ea-9f4a-d381af1fdbc1.png)

**Comment by ai6bx** [comment]
I have restarted OLSR from the advanced tab a few times when I first updated this node as it was one of the most persistent in not showing the node name and rather only the IP address. Occasionally after a reboot or restart, it will show as dtd but then reverts back.

**Comment by ae6xe** [comment]
duplicate, tracked on another issues.
