### ISSUE TITLE
Enhancement request: Packages repository

### ISSUE THREAD

**Issue by xJMV** [aredn/aredn_ar71xx#526]
Just like #452, packages should also be able to be retrieved from the mesh or whatever URL specified in the advanced settings.

**Comment by r1de** [comment]
The newer nightly builds ( > 3.20.3.0 ) should have this ability.
See the advanced config page:
![Advanced Config Page](https://kg6wxc.net/pics/AREDN_DOWNLOAD_PATHS.png)
You have to set each one individually (they could be in different places! :smile: )

**Comment by xJMV** [comment]
Oh did not load any nodes with nightly... Sorry for that... No way to use list files ?

**Comment by r1de** [comment]
not for the packages I do not think.
`opkg` uses the `/etc/opkg/distfeeds.conf` file to get the list of packages.
It's similar to apt and different than the firmware downloads.
I could be wrong though, I am not sure of the inner workings of `opkg`.

**Comment by xJMV** [comment]
Lost to all this, will close the ticket. Thanks @r1de :)
