### ISSUE TITLE
Remove Grid Square entry

### ISSUE THREAD

**Issue by Orv** [aredn/aredn_ar71xx#534]
Remove entry on Setup screen for Grid Square; it's too coarse for accurate node location and isn't used anywhere anyway.

**Comment by ae6xe** [comment]
Closing consistent with #536.   Grid Square and lat/lon are not used by the node itself, however some subset of the community may find one or both useful.   lat/lon is useful to plot maps.  grid square is a quick lookup to find possible neighbor links within the same or adjacent grid square.
