### ISSUE TITLE
WAN ok but no download firmware list on rb-952ui-5ac2nd (hAP ac lite)

### ISSUE THREAD

**Issue by leonardinux** [aredn/aredn_ar71xx#547]
Trying to refresh firmware list an error is taken, see below.
Package refresh works fine.
That's it!

Firmware Update
--
Downloading firmware list from http://downloads.arednmesh.org/firmware... Downloading 'http://downloads.arednmesh.org/firmware/firmware.rb-952ui-5ac2nd.list' Connecting to 165.227.210.227:80 Writing to '/tmp/web/firmware.list'  /tmp/web/firmware.li     0  --:--:-- ETA /tmp/web/firmware.li     0  --:--:-- ETA /tmp/web/firmware.li     0  --:--:-- ETA /tmp/web/firmware.li     0  --:--:-- ETA /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li      0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li      0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled  - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0    - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0    - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li      0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li      0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li      0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled  - /tmp/web/firmware.li     0   - stalled -Connection error: Connection timed out | Downloading firmware list from http://downloads.arednmesh.org/firmware... Downloading 'http://downloads.arednmesh.org/firmware/firmware.rb-952ui-5ac2nd.list' Connecting to 165.227.210.227:80 Writing to '/tmp/web/firmware.list'  /tmp/web/firmware.li     0  --:--:-- ETA /tmp/web/firmware.li     0  --:--:-- ETA /tmp/web/firmware.li     0  --:--:-- ETA /tmp/web/firmware.li     0  --:--:-- ETA /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li      0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li      0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled  - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0    - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0    - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li      0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li      0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li      0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled  - /tmp/web/firmware.li     0   - stalled -Connection error: Connection timed out
Downloading firmware list from http://downloads.arednmesh.org/firmware... Downloading 'http://downloads.arednmesh.org/firmware/firmware.rb-952ui-5ac2nd.list' Connecting to 165.227.210.227:80 Writing to '/tmp/web/firmware.list'  /tmp/web/firmware.li     0  --:--:-- ETA /tmp/web/firmware.li     0  --:--:-- ETA /tmp/web/firmware.li     0  --:--:-- ETA /tmp/web/firmware.li     0  --:--:-- ETA /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li      0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li      0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled  - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0    - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0    - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li      0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li      0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li      0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled - /tmp/web/firmware.li     0   - stalled  - /tmp/web/firmware.li     0   - stalled -Connection error: Connection timed out
current version: 3.20.3.0
hardware type: mikrotik (rb-952ui-5ac2nd)

**Comment by dman776** [comment]
added .list file
