### ISSUE TITLE
Nightly build directory is empty.

### ISSUE THREAD

**Issue by Orv** [aredn/aredn_ar71xx#65]

**Comment by ae6xe** [comment]
Orv, the build directory structure is changed to correct another issue (the package refresh from setup wasn't working).  We had a missing level that now exists, so the path you have been using is changed.

**Comment by ae6xe** [comment]
http://downloads.arednmesh.org/snapshots/trunk/targets/ar71xx/generic/

**Comment by Orv** [comment]
That URL works, Joe.  

The URL is advertised as http://downloads.arednmesh.org/snapshots/trunk/ar71xx/generic/ on arednmesh.org  but I get:

The requested URL /snapshots/trunk/ar71xx/generic/ was not found on this server.****
when clicking on the Nightly Builds link.

**Comment by ae6xe** [comment]
We're not done with the path change :), to the web site links.  Thanks for
pointing that out.

**Comment by ae6xe** [comment]
...actually,  that link is updated.  You may need to clear your browser cache?
