### ISSUE TITLE
Bug: Hostnames/DHCP

### ISSUE THREAD

**Issue by r1de** [aredn/aredn_ar71xx#66]
The scripts that generate the olsrd.conf file are not adding the "PlParam" line for the dhcp lease hosts.
ie: `PlParam "10.96.124.140" "kg6wxc-host"`

The hostname never gets propagated out over the mesh without that entry.
The service listings get hosed as well, they do not show up in the GUI, nor out on the mesh.

I'm not sure I can fix this one... I defer to you guys. :smile:

**Comment by ae6xe** [comment]
Can you confirm this is occurring when this host has an AREDN advertised service on this host?

**Comment by r1de** [comment]
Yes, even when I had multiple services listed for the host(s), none of them would show up.
The IP was also unresolveable on the other side of the mesh, I could resolve it locally just fine though.
W6BI witnessed this and can attest to it.

Once I sort of "hacked" those entries into my olsrd.conf file and restarted olsrd everything was normal again. :smile:

**Comment by ae6xe** [comment]
thanks for catching that, we'll take a look at.

**Comment by r1de** [comment]
Thanks!
I was pulling my hair out all morning trying to figure out what the heck went wrong.

This is the relevant part of the affected olsrd.conf file:
(as you can see the service is listed, but the ip for the host is not)

LoadPlugin "olsrd_nameservice.so.0.4"
{
    PlParam "sighup-pid-file" "/var/run/dnsmasq/dnsmasq.pid"
    PlParam "interval" "30"
    PlParam "timeout" "300"
    PlParam "name-change-script" "touch /tmp/namechange"
    PlParam "name" "KG6WXC-VC-PTH-5G-X"
    PlParam "10.145.121.127" "dtdlink.KG6WXC-VC-PTH-5G-X.local.mesh"
    PlParam "service" "http://kg6wxc-test-fake:80/bunk|tcp|thisIsFake"
}

**Comment by ae6xe** [comment]
This might be related to the fact that "nslookup" output is different.
There are a few places where the code turns a hostname into an IP address,
and we screen scrape the output of nslookup.   The format has changed and
the parsing needs udpated.  This could be in the olsr init scripts or
somewhere under /www/cgi-bin/.

**Comment by r1de** [comment]
I could be totally wrong (and probably am), but I can't see how nslookup would come into play in this instance.
The hostname/IP combo does not exist until it is created by the user, there isn't anything to look up until it is already created.

(just my thoughts)

**Comment by ae6xe** [comment]
The local node has an /etc/hosts file entry when the hostname/IP is reserved in setup.   Checkout /usr/local/bin/olsrd-config -- it generates these olsr.conf settings.   It is calling ip2hostname in /www/cgi-bin/perlfunc.pm .   It couldn't get an IP address back with the bad parsing.
