### ISSUE TITLE
Trim unnecessary packages to save memory resources

### ISSUE THREAD

**Issue by dman776** [aredn/aredn_ar71xx#81]

**Comment by dman776** [comment]
IPV6
SNMP
others?

**Comment by Orv** [comment]
Not SNMP please.  We use it heavily to monitor our network performance.  (Pulling it from the 32MB image would be OK, just not the 64 MB).

**Comment by r1de** [comment]
That works for me.
what about removing the usb support is it actually needed?
kmod-usb-uhci
kmod-usb-ohci
kmod-usb-core

and what about these 2:
odhcpd-ipv6only
libip6tc

**Comment by Orv** [comment]
SNMP as an option would be OK.  We'd mostly want to monitor high-level nodes and they'll all be 64 MB devices.

**Comment by r1de** [comment]
I have been experimenting. :smile:

**libip6tc** should not be removed yet, iptables breaks when it is not available. Oddness occurs.

**kmod-usb*** I made into modules, there are 5 of em.

**tcpdump-mini** and **libpcap** can both be made into modules.
Most "normal" users are never going to need them, and those of us who do can install it if/when needed.

**smnpd** and **libnetsnmp** I also made into modules just to see.

With all those removed the resulting image is about 5.7MB, when loaded I had 1.5MB left in my "flash" area on an old RocketM2.
Even after installing tunnels there is still about 700K left free in "flash"!

Everything is working fine. Even the tunnels.

I am sure there are a few more packages that this can be done too...
Just don't try to remove libip6tc!!
The line about libip6tc should be removed from common.config just in case!

**Comment by r1de** [comment]
I can't stop messing with this...
I am pretty sure I removed *all* ipv6 now.
Image file down only a little bit this time, to 5.6M.

I was able to build an image and load it onto an old NSM2 I have, and it is working just fine it seems so far. (Even on the large So. Cal. network)
The NSM2 still has about 5.5MB free in Memory and about 1.6MB free in Flash.

I'm not sure this should be called "done" until there is more testing tho.

**Comment by dman776** [comment]
submit the PR and we can start reviewing it

**Comment by r1de** [comment]
I will, but now that I said something, I am double checking some things first. :smile:

**Comment by Orv** [comment]
I loaded Eric's firmware version on an old 32 MB NSM2 and it seems to be running well (I found one possible bug unrelated to his work that we'll open an issue on.
So far so good...
