### ISSUE TITLE
Point Firmware Update Version Check to Github

### ISSUE THREAD

**Issue by mikewren** [aredn/aredn_ar71xx#82]
v3.16.1.1 is hardcoded to query arden.org when doing a latest version check via the Administration page (/cgi-bin/admin), and will optionally download and install firmware updates available via this domain.

Firmware update should query project page on Github.

**Comment by dman776** [comment]
This has already been completed and closed in pull request #47

**Comment by mikewren** [comment]
My bad, didn't see $47, I'm still getting re-acquainted with Github. Keep up the great work!
