### ISSUE TITLE
Node Description Improvement #3

### ISSUE THREAD

**Issue by Orv** [aredn/aredn_ar71xx#91]
Make the Node Description entry field multi-line, so the entire allowable string length can be viewed (wrap entry at end of each field line).

**Comment by r1de** [comment]
How about just allowing one tag, `<br/>`?
Let the user format the thing themselves, kinda sorta...

**Comment by n2mh** [comment]
You may also wish to provide a means for a club or  organization to upload their logo. I would suggest a locatiion on the top right of a node's screen, positioned similar to the AREDN logo and sized accordingly.
