### ISSUE TITLE
OLSR Status Button missing from main screen

### ISSUE THREAD

**Issue by Orv** [aredn/aredn_ar71xx#92]
Was this intentional?

**Comment by dman776** [comment]
This was intentional.  There was a flaw in that plugin.  You can get the info from the Json plugin on port 9090.  It’s removal also saves memory on the node

Thanks,
Darryl

**Comment by ae6xe** [comment]
Yes, removed by design.  This plugin is not scalable and will trigger OLSR restarts and has made a node unresponsive on at least one occasion.
