### ISSUE TITLE
Apostrophe in Node Description string truncates string at apostrophe

### ISSUE THREAD

**Issue by Orv** [aredn/aredn_ar71xx#97]
Is that the expected behavior?  I hope not - it would nice to be able to use " ' " in a description string.

**Comment by r1de** [comment]
saved from the apostropocalypse!

See Pull Request #98 

It's apostrophantasic!
(sorry, I couldn't resist :smile: )

**Comment by ae6xe** [comment]
This issue fixed with 22e4557
